[dependencies]
clap = { version = "3.0", features = ["wrap_help"] }
windows = { version = "0.45", features = ["Win32_Foundation", "Win32_Security_Authorization", ...] }
tokio = { version = "1.1", features = ["full"] }
winapi = "0.3"
winrt = "0.19"